1. Create a 3x3 array that contains a diagonal of nines.


In [1]:
import numpy as np

fun = np.identity(3)*9
print(fun)

[[9. 0. 0.]
 [0. 9. 0.]
 [0. 0. 9.]]


2. Create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive) and use Boolean indexing to pick out the values that are within 1/2 standard deviations of the mean.


In [11]:
import numpy as np

arr = np.arange(2, 33, 2).reshape(4, 4)
print("Original array:\n", arr)

mean = np.mean(arr)
std = np.std(arr)

mask = np.abs(arr - mean) <= (0.5 * std)
values = arr[mask]
print()
print("Values within ±0.5 std of mean:\n", values)


Original array:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

Values within ±0.5 std of mean:
 [14 16 18 20]


3. Create a 9x9 array that contains only zero of type int.


In [19]:
arr = np.zeros((9,9))
print(arr)
arr = arr.astype(int)
print(f'\n {np.dtype(arr[0][0])}')

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 int64


4. Ask the user for a number n. Then, use broadcasting to create a n x n ndarray that has its first column full of ones, its second column full of twos, its third column full of threes, etc…

In [22]:
import numpy as np

n = int(input())

arr = np.arange(1, n+1)

result = np.tile(arr, (n, 1))

print(result)


[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


5- https://codeforces.com/contest/381/problem/A

In [ ]:
n = int(input())
arr = list(map(int, input().split()))

serage, dima = 0, 0
beg, end = 0, n - 1

while beg <= end:
    if max(arr[beg], arr[end]) == arr[beg]:
        serage += arr[beg]
        beg += 1
    else:
        serage += arr[end]
        end -= 1

    if beg > end:
        break

    if max(arr[beg], arr[end]) == arr[beg]:
        dima += arr[beg]
        beg += 1
    else:
        dima += arr[end]
        end -= 1

print(serage, dima)


6- https://codeforces.com/contest/707/problem/A

In [ ]:
n, m = map(int, input().split())

arr = []
for _ in range(n):
    row = input().split()
    arr.append(row)

is_colored = False

for i in range(n):
    for j in range(m):
        if arr[i][j] not in ['W', 'B', 'G']:
            is_colored = True
            break
    if is_colored:
        break

if is_colored:
    print("#Color")
else:
    print("#Black&White")
